name: surprisal
channels:
  - pytorch
  - huggingface
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - loguru
  - gpustat
  - pytorch-cuda
  - pytorch
  - transformers=4.48
  - spacy
  - ruff
  - wordfreq
  - matplotlib
  - sentencepiece
  - openpyxl
  - scipy
  - pip:
    - git+https://github.com/lacclab/text-metrics.git
    - mamba-ssm
    - causal-conv1d
    - -e .